/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 public/models/Explosion2/Explosion2.gltf -o app/components/sub/Explosion2.jsx 
Author: andersdt (https://sketchfab.com/andersdt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/explosion-46fb54741fbc4cc0854c03b5ef5d0624
Title: Explosion
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Explosion(props) {
  const { nodes, materials } = useGLTF("/models/Explosion/Explosion.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Explosion_1.geometry} material={materials.Fire} />
        <mesh
          geometry={nodes.Explosion_pointy_1.geometry}
          material={materials.Fire_pointy}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Explosion/Explosion.gltf");
