/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Spanner/Spanner.gltf -o app/components/sub/Spanner.jsx -r public 
Author: CGWorker (https://sketchfab.com/CGWorker)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/adjustable-spannerwrench-e13f98a9d7364510a65042d4c42e7a9c
Title: Adjustable Spanner/Wrench
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Spanner(props) {
  const { nodes, materials } = useGLTF("/models/Spanner/Spanner.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, Math.PI / 4, Math.PI / 12]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.initialShadingGroup}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Spanner/Spanner.gltf");
