/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Astronaut/Astronaut.gltf -o app/components/sub/Astronaut.jsx -r public 
Author: IronEqual (https://sketchfab.com/ie-niels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/astronaut-from-poly-by-google-255536005c354e81a2347418a4be413d
Title: Astronaut from Poly by Google
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Astronaut(props) {
  const { nodes, materials } = useGLTF("/models/Astronaut/Astronaut.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Astronaut_mat}
        rotation={[0, (-2 * Math.PI) / 3, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/Astronaut/Astronaut.gltf");
